### ISSUE TITLE
When does the generator close vinyl streams? (error with gulp-typescript)

### ISSUE THREAD

**Issue by mattdsteele** [yeoman/generator#1030]
My use case: I'm building a generator with an option to emit TypeScript or JavaScript code. The original files are written in TypeScript. If they choose to emit JS code, I'd like to run the TypeScript compiler against the files and emit the results. I'm attempting to follow the "Transforming output files" pattern [here](http://yeoman.io/authoring/file-system.html).

I'm trying to do this with `gulp-typescript`:

```javascript
      writing() {
        const filter = require('gulp-filter');
        const ts = require('gulp-typescript');
        const tsFilter = filter(['**/*.ts'], { restore: true });
        this.registerTransformStream(tsFilter);
        this.registerTransformStream(ts({
          noEmitOnError: false,
          target: 'es2015',
          module: 'es2015',
          allowJs: true
        }));
        this.registerTransformStream(tsFilter.restore);
      }
```

But when I run the generator with a project that includes TS files (like `src/index.ts`), it fails:

```
   create src\index.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:156:17)
    at CompileOutputStream.Readable.push (_stream_readable.js:134:10)
    at Output.writeJs (generator-test\node_modules\gulp-typescript\release\output.js:25:23)
    at ProjectCompiler.emitFile (generator-test\node_modules\gulp-typescript\release\compiler.js:135:33)
    at ProjectCompiler.inputDone (generator-test\node_modules\gulp-typescript\release\compiler.js:76:22)
    at CompileStream.end (generator-test\node_modules\gulp-typescript\release\project.js:136:31)
    at onend (generator-test\node_modules\readable-stream\lib\_stream_readable.js:498:10)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This pattern (filter, run gulp plugin, restore filter) works for other tools (like gulp-jade), so it makes me think the TypeScript compiler is finishing its work after the vinyl stream is closed (as I see `src/index.js` has already been created from `src/index.ts`)

Any ideas how I could resolve this? Would moving the compilation earlier in the Yeoman lifecycle help things out, perhaps?

**Comment by mattdsteele** [comment]
Based on the stack [and these lines of code](https://github.com/ivogabe/gulp-typescript/blob/master/lib/project.ts#L175-L187), it looks like gulp-typescript writes files on the stream's `end`, which is probably the root issue.

Not really sure how to resolve this?

**Comment by mattdsteele** [comment]
Closing - see my solution in https://github.com/ivogabe/gulp-typescript/issues/531
