### ISSUE TITLE
problem when using "yo ionic"

### ISSUE THREAD

**Issue by lu1sm4st3r** [yeoman/generator#1091]
Would you like to use Sass with Compass (requires Ruby)? No
? Which Cordova plugins would you like to include? org.apache.cordova.device, org.apache.cordova.console
, com.ionic.keyboard
? Which starter template would you like to use? Tabs
HTTP error 404 retrieving version 3.6.3 of cordova for www: Skipping `cordova create`

Install plugins registered at plugins.cordova.io: grunt plugin:add:org.apache.cordova.globalization
Or install plugins direct from source: grunt plugin:add:https://github.com/apache/cordova-plugin-console.git

Installing selected Cordova plugins, please wait.
{ CordovaError: Current working directory is not a Cordova-based project.
    at Object.cdProjectRoot (C:\Users\Adm\AppData\Roaming\npm\node_modules\generator-ionic\node_modules\cordova-lib\src\cordova\util.js:119:15)
    at Object.plugin (C:\Users\Adm\AppData\Roaming\npm\node_modules\generator-ionic\node_modules\cordova-lib\src\cordova\plugin.js:35:36)
    at Object.module.exports.(anonymous function) [as plugin] (C:\Users\Adm\AppData\Roaming\npm\node_modules\generator-ionic\node_modules\cordova-lib\src\cordova\util.js:260:21)
    at constructor.installPlugins (C:\Users\Adm\AppData\Roaming\npm\node_modules\generator-ionic\app\index.js:148:19)
    at C:\Users\Adm\AppData\Roaming\npm\node_modules\generator-ionic\node_modules\yeoman-generator\lib\base.js:409:16
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  name: 'CordovaError',
  message: 'Current working directory is not a Cordova-based project.' }
× Please run `yo ionic` in an empty directory, or in that of an already existing cordova project.

**Comment by SBoudrias** [comment]
Please report bugs happening while running a generator on the specific generator repository.

The Yeoman team works owns the core system and cannot maintain all of the ~8000 publicly available generators 😄
