### ISSUE TITLE
kraken.js not creating new project on ubuntu

### ISSUE THREAD

**Issue by immaculatesoftsolutions** [yeoman/generator#1198]
I have installed kraken js on my ubuntu machine. Now I am creating new project using `yo kraken` command so its showing below error.

```
00h00m00s 0/0: : fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (/usr/lib/node_modules/generator-kraken/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/lib/node_modules/generator-kraken/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/lib/node_modules/generator-kraken/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by mshima** [comment]
This error is should be posted at generator-kraken project.
