### ISSUE TITLE
TypeError: self.prompt is not a function when webpack-cli init

### ISSUE THREAD

**Issue by hyaocuk** [yeoman/generator#1226]
I'm currently learning how to build my own generator for webpack-cli following the instructions: https://webpack.js.org/contribute/writing-a-scaffold/

I tried to run <code>webpack-cli init ../webpack-scaffold-react1</code>, it seems to throw an error from Yeoman:

```console
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: self.prompt is not a function
    at List (/Users/hyaocuk/Documents/CS/Frontend/Scaffold/webpack-scaffold-react1/node_modules/@webpack-cli/webpack-scaffold/index.js:51:17)
    at WebpackGenerator.prompting (/Users/hyaocuk/Documents/CS/Frontend/Scaffold/webpack-scaffold-react1/index.js:18:13)
    at Object.<anonymous> (/Users/hyaocuk/Documents/CS/Frontend/Scaffold/webpack-scaffold-react1/node_modules/yeoman-generator/lib/index.js:816:25)
    at /Users/hyaocuk/Documents/CS/Frontend/Scaffold/webpack-scaffold-react1/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/hyaocuk/Documents/CS/Frontend/Scaffold/webpack-scaffold-react1/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/hyaocuk/Documents/CS/Frontend/Scaffold/webpack-scaffold-react1/node_modules/yeoman-generator/lib/index.js:817:11)
    at processImmediate (internal/timers.js:456:21)
Emitted 'error' event on WebpackGenerator instance at:
    at Immediate.<anonymous> (/Users/hyaocuk/Documents/CS/Frontend/Scaffold/webpack-scaffold-react1/node_modules/yeoman-generator/lib/index.js:852:20)
    at processImmediate (internal/timers.js:456:21)
```

the generator index.js
```javascript
module.exports = class WebpackGenerator extends Generator {
/* constructor */
prompting() {
        return this.prompt([
            List('confirm', 'Welcome to the demo scaffold! Are you ready?', ['Yes', 'No', 'Pengwings']),
            Input('entry', 'What is the entry point in your app?')
        ]).then(answer => {
            if (answer['confirm'] === 'Pengwings') {
                this.options.env.configuration.dev.webpackOptions = createDevConfig(answer);
            }
        })
    }
}
```

I tried the latest @webpack-cli/init and @webpack-cli/init@0.2.2, but encountered the same error eventually.

Thank you~

---
I use **nvm**
Node: V14.0.0
npm: 6.14.4
yo: 3.1.1

**Comment by mshima** [comment]
I don't know if I can help much here, but looking at: https://github.com/webpack/webpack-cli/blob/4fd900556ad1d9c87ca04fe0ebccb78dd89ea6c2/packages/webpack-scaffold/src/index.ts#L55-L61

Looks like it should be `List(this, 'confirm', ...` instead of `List('confirm', ...`

**Comment by hyaocuk** [comment]
> I don't know if I can help much here, but looking at: https://github.com/webpack/webpack-cli/blob/4fd900556ad1d9c87ca04fe0ebccb78dd89ea6c2/packages/webpack-scaffold/src/index.ts#L55-L61
> 
> Looks like it should be `List(this, 'confirm', ...` instead of `List('confirm', ...`

Thank you, @mshima, it shed light on how I'm going to resolve this issue, I should follow the instruction: https://yeoman.io/authoring/user-interactions.html
It's a little bit different from the one in webpack-cli.

Anyway, thank you very much! **SOLVED**
