### ISSUE TITLE
Crash when space in yeoman generator path

### ISSUE THREAD

**Issue by nvuillam** [yeoman/generator#1314]
A mega-linter user detected a crash in the generator because there is a space in its windows username

Please could you check ?

```
C. A. M. Gerlach@QUASIMODO MINGW64 ~/Documents/dev/SpaceX/submanager (master)
$ npx mega-linter-runner@beta --install
Yeoman generator used: C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\generators\mega-linter
C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:747
        throw new Error(
              ^

Error: You don't seem to have a generator with the name “C:\Users\C.” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-C:\Users\C..

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at checkGenerator (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:747:15)
    at Environment.create (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:774:29)
    at instantiateAndRun (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:987:36)
    at Environment.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\yeoman-environment\lib\environment.js:1004:12)
    at MegaLinterRunner.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\runner.js:47:11)
    at MegaLinterRunnerCli.run (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\cli.js:11:34)
    at C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\index.js:13:37
    at Object.<anonymous> (C:\Users\C. A. M. Gerlach\AppData\Local\npm-cache\_npx\bcc0ed12329339b9\node_modules\mega-linter-runner\lib\index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
```

Thanks :)

https://github.com/nvuillam/mega-linter/issues/676

**Comment by CAM-Gerlach** [comment]
In addition, I tested a global install, and ran into the same issue running it on Windows. In this case, it seems it will likely occur for any Windows user installing globally (at least that has npm installed in the standard `Program Files` location) because the `Program Files` directory contains a a space.

```python-traceback
C. A. M. Gerlach@QUASIMODO MINGW64 ~/Documents/dev/SpaceX/submanager (update-cis-post-060)
$ mega-linter-runner --install
C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:630
        new Error(
        ^

Error: You don't seem to have a generator with the name “C:\Program” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/.
Install them with npm install generator-C:\Program.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators.

If yo cannot find the generator, run yo doctor to troubleshoot your system.
    at Environment.create (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:630:9)
    at instantiateAndRun (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:729:30)
    at Environment.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\node_modules\yeoman-environment\lib\environment.js:758:12)
    at MegaLinterRunner.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\runner.js:43:11)
    at MegaLinterRunnerCli.run (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\cli.js:11:34)
    at C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\index.js:13:37
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\mega-linter-runner\lib\index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
```

**Comment by CAM-Gerlach** [comment]
As far as I am aware, this is still a critical bug.

**Comment by nvuillam** [comment]
Not stale ? :)
