### ISSUE TITLE
Call subgenerator twice or more times

### ISSUE THREAD

**Issue by AlekseyLeshko** [yeoman/generator#1592]
Hello! Firstly, thank you for yeoman!

My subgenerator create some files base on files in  templates folder.
```
this.fs.copyTpl(...);
```

I try to call subgenerator in may main generator.
If I call once
```
this.composeWith(require.resolve('../generatorX'), {
  arguments: ['xxx'],
  params: 'test-params',
});
```
All right, not errors. I have all files from subgenerator templates folder.

And if I call subgenerator twice or more
```
this.composeWith(require.resolve('../generatorX'), {
  arguments: ['xxx'],
  params: 'test-params',
});
this.composeWith(require.resolve('../generatorX'), {
  arguments: ['yyy'],
  params: 'test-params',
});
```
I have some error
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /xxx/generators/xxx/templates/**
    at EditionInterface.exports._copySingle (/xxx/node_modules/mem-fs-editor/lib/actions/copy.js:57:3)
    at files.forEach.file (/xxx/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/xxx/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at EditionInterface.module.exports [as copyTpl] (/xxx/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at module.exports.writing (/xxx/generators/xxx/index.js:29:13)
    at Object.<anonymous> (/xxx/node_modules/yeoman-generator/lib/index.js:399:25)
    at /xxx/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /xxx/node_modules/run-async/index.js:24:19
```

Most likely, locking files while reading.
How wrap subgenerator in promise? How wait until the completion of the subgenerator?

Thankyou for answers and help!

**Comment by mshima** [comment]
A lot has changed.
I suggest to:
- use `this.destinationPath` instead of custom dest.
- use new generator apis: `this.copyDestination` for files and `this.renderDestination` for ejs templates.

There are tests for glob patterns and duplicate files now:
https://github.com/SBoudrias/mem-fs-editor/blob/0287fe274d1573eaf11c4c38f2d9eb23673a9aeb/src/actions/copy-async.ts#L80-L82
