### ISSUE TITLE
Invoke error: Did not provide required argument name

### ISSUE THREAD

**Issue by awinogradov** [yeoman/generator#508]
I see this when new empty sub generator invoked from main index.js:

``` bash
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Did not provide required argument name!
    at InitGenerator.argument (/Users/verybigman/Projects/generator-bem/node_modules/yeoman-generator/lib/base.js:235:31)
    at InitGenerator.NamedBase (/Users/verybigman/Projects/generator-bem/node_modules/yeoman-generator/lib/named-base.js:16:8)
    at new InitGenerator (/Users/verybigman/Projects/generator-bem/init/index.js:15:33)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-generator/lib/env/index.js:252:10)
    at BemGenerator.invoke (/Users/verybigman/Projects/generator-bem/node_modules/yeoman-generator/lib/actions/invoke.js:18:28)
    at BemGenerator.installDependencies.callback (/Users/verybigman/Projects/generator-bem/app/index.js:79:22)
    at /Users/verybigman/Projects/generator-bem/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at /Users/verybigman/Projects/generator-bem/node_modules/yeoman-generator/node_modules/async/lib/async.js:119:25
    at /Users/verybigman/Projects/generator-bem/node_modules/yeoman-generator/node_modules/async/lib/async.js:24:16
    at /Users/verybigman/Projects/generator-bem/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
```

I invoke InitGenerator by this:

``` javascript
this.invoke("bem:init", {options: {nested: true, appName: this.appName}});
```

**Comment by vt5491** [comment]
Concrete example passing a name to angular:controller subgenerator:

this.composeWith('angular:controller',  {args: ['myControllerName']} );
