### ISSUE TITLE
Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by takotuesday** [yeoman/generator#747]
On the upgrade from v0.18.6 to v0.18.7 my unit tests break. Here is the trace:
```bash
Running "mochaTest:test" (mochaTest) task


  node-service:app
    ✓ can be required without throwing (94ms)
    generating
      1) creates files
      2) calcOption


  1 passing (208ms)
  2 failing

  1) node-service:app generating creates files:
     Uncaught TypeError: Cannot read property 'dependencies' of undefined
      at yeoman.generators.Base.extend.install.dependencies (/home/user/jogriffin/tempFiles/generator-node-service/generators/app/index.js:9:7223)
      at /home/user/jogriffin/tempFiles/generator-node-service/node_modules/yeoman-generator/lib/base.js:408:16
      at processImmediate [as _immediateCallback] (timers.js:330:15)

  2) node-service:app generating calcOption:
     Uncaught TypeError: Cannot read property 'dependencies' of undefined
      at yeoman.generators.Base.extend.install.dependencies (/home/user/jogriffin/tempFiles/generator-node-service/generators/app/index.js:9:7223)
      at /home/user/jogriffin/tempFiles/generator-node-service/node_modules/yeoman-generator/lib/base.js:408:16
      at processImmediate [as _immediateCallback] (timers.js:330:15)



Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.
Warning: Command failed: Loading config: /home/user/jogriffin/tempFiles/generator-node-service/.istanbul.yml
 Use --force to continue.

Aborted due to warnings.
```

**Comment by SBoudrias** [comment]
Well, what's on this line? `generator-node-service/generators/app/index.js:9`

**Comment by takotuesday** [comment]
I do not think line 9 where  is behind the issue: 
```javascript
var validServiceName          =  new RegExp('^[a-z0-9_-]+$');
var validServiceDescription  = new RegExp('^[A-Z].+\\.$');
var validGitlabGroup            = validServiceName;
```
The problem seems to arise from this snippet:
```javascript
var dependencies = this.fs.readJSON(this.templatePath('../partials/dependencies.json'));
var generatedPackage = this.fs.readJSON(this.destinationPath('package.json'));

 _.extend(generatedPackage.dependencies, dependencies.dependencies);
```

**Comment by SBoudrias** [comment]
@takotuesday Not sure what issue here is... But when you use the `ready` event to write a file on disk, if another generator already loaded that file into the memory file-system, it won't be refreshed. The generator is instantiated before `ready` is called. So make sure the files you create in the `ready` callback haven't been used in the `constructor` (if so, move these calls to the `initializing` phase).

Let me know if this helps

**Comment by joeybaker** [comment]
@destroyerofbuilds asked me to post what I'm seeing. This is the stack trace. 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: object is not a function
    at null.<anonymous> (/node_modules/yeoman-generator/lib/base.js:382:5)
    at Queue.g (events.js:180:16)
    at Queue.emit (events.js:92:17)
    at Queue.<anonymous> (/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/grouped-queue/lib/queue.js:68:12)
    at Queue.next (/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/grouped-queue/lib/queue.js:79:43)
    at SubQueue.run (/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/grouped-queue/lib/subqueue.js:41:45)
    at Queue.next (/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/grouped-queue/lib/queue.js:80:39)
    at SubQueue.run (/node_modules/yeoman-generator/node_modules/yeoman-environ
```

To replicate:

1. `git pull https://github.com/joeybaker/generator-iojs`
2. `npm i && npm i yeoman-generator@latest`
3. `npm test`

**Comment by SBoudrias** [comment]
@joeybaker I don't see how your trace relate to the one being discussed here...?

**Comment by SBoudrias** [comment]
@takotuesday did my last comment fixed your issue?

**Comment by SBoudrias** [comment]
Closing as inactive.

**Comment by destroyerofbuilds** [comment]
@SBoudrias, a little more information now that I'm getting back to working on the issue encountered by @takotuesday.

In my `install` group, I have a function called `dependencies`. In that function I do the following:


```javascript
var generatedPackage = this.fs.readJSON(this.destinationPath('package.json'));
```

This was shown by @takotuesday in his second comment. If I output the content of `generatedPackage` on the next line, I get `undefined`:

```javascript
console.log('Generated: ', generatedPackage);
```

However, if I, on the line before getting the `package.json` content, I call the following:

```javascript
console.log('Required: ', require(this.destinationPath('package.json')));
```

I get the contents of the `package.json` file as generated by the `on('ready')` callback function (again, as shown by @takotuesday ).

**Comment by destroyerofbuilds** [comment]
Also, the `on('ready')` now looks like the following:

```javascript
                .on('ready', function (generator) {
                    var done = this.async();
                    var packageFile = require(path.join(__dirname, '../templates/common/package.json'));

                    packageFile.name = PROMPTS.moduleName;

                    fs.writeFile(generator.destinationPath('package.json'), JSON.stringify(packageFile), done);
                })
```

**Comment by destroyerofbuilds** [comment]
So apparently `this.fs.exists(this.destinationPath('package.json'))` returns false, though `this.fs.readJSON` doesn't throw an exception as documented`.

Should I be using `generator.fs` in the `on('ready')` callback?

**Comment by SBoudrias** [comment]
@destroyerofbuilds that's a valid option.

The issue though might be that you're reading file in your generator constructor.

**Comment by destroyerofbuilds** [comment]
@SBoudrias, a slightly modified version of my `constructor`:

```javascript
    constructor: function () {
        generators.Base.apply(this, arguments);

        this.option('skip-install', {
            type: 'Boolean',
            defaults: false,
            desc: 'Disable the \'npm install\' step after the generator has finished scaffolding project files.'
        });

        this.option('moduleName', {
            type: 'String',
            defaults: this.config.get('moduleName') || _.kebabCase(this.appname),
            desc: 'Module Name, Project name and subsequently the GitLab repository name.'
        });

        this.option('moduleDescription', {
            type: 'String',
            defaults: this.config.get('moduleDescription'),
            desc: 'A detailed description of your project and its purpose.'
        });

        this.option('cliTool', {
            type: 'Boolean',
            defaults: _.isBoolean(this.config.get('cliTool')) ? this.config.get('cliTool') : false,
            desc: 'Scaffold an executable file for use as a CLI tool.'
        });

        this.option('mainOption', {
            type: 'Boolean',
            defaults: false,
            desc: 'Scaffold example usage file for this module.'
        });

    },
```

I removed one call to `this.option`.

**Comment by SBoudrias** [comment]
Oh, there's no `this.async()` in the ready callback. Use sync methods to write files.

**Comment by destroyerofbuilds** [comment]
As shown in [my comment](https://github.com/yeoman/generator/issues/747#issuecomment-92478855), I call `var done = this.async()` and then pass it to `fs.writeFile`.

Now, I've modified my `on('ready')` function to look like the following:

```javascript
                .on('ready', function (generator) {
                    var packageFile = generator.fs.readJSON(path.join(__dirname, '../templates/common/package.json'));

                    packageFile.name = PROMPTS.moduleName;

                    generator.fs.writeJSON(generator.destinationPath('package.json'), packageFile);
                })
```

**Comment by destroyerofbuilds** [comment]
The switch to `generator.fs.writeJSON` is working. I can retrieve the written content from the install function in my generator using `this.fs.readJSON`.

Now I'm running into other issues with my generator (so many reads and writes going on), and I'm trying to make sure it's not related to this issue.

**Comment by destroyerofbuilds** [comment]
Running into another issue related to switching out how I write fixture data.

In my generator, I have the following function that is working just fine now (after the switch in the `on('read')` function:

```javascript
    install: {
        dependencies: function () {
            var dependencies = this.fs.readJSON(this.templatePath('../partials/dependencies.json'));
            var generatedPackage = this.fs.readJSON(this.destinationPath('package.json'));

            _.extend(generatedPackage.dependencies, dependencies.dependencies);
            _.extend(generatedPackage.devDependencies, dependencies.devDependencies);

            this.fs.writeJSON(this.destinationPath('package.json'), generatedPackage);
        },
```

However, execution never gets to the next install function. The following exception is thrown:

```javascript
/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Property 'undefined' of object spy is not a function
    at Conflicter.<anonymous> (/home/user/hbetts/workspace/generator-node-module/node_modules/yeoman-generator/lib/util/conflicter.js:187:36)
    at PromptUI.onCompletion (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:1977:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)
    at AnonymousObserver.tryCatcher (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:5032:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)
    at InnerObserver.onCompleted (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:3345:65)
    at InnerObserver.tryCatcher (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/user/hbetts/workspace/generator-node-module/node_modules/inquirer/node_modules/rx/dist/rx.js:5032:56)
```

Am I essentially creating an unresolvable file conflict because of the way I'm writing fixture data?

**Comment by destroyerofbuilds** [comment]
I'm calling `generator.conflicter.force = true;` in my `on('ready')` callback function.

That seems to allow my tests to complete with success. I assume that option, based on a StackOverflow post, tells Yeoman to always accept changes caused by the generator.

@SBoudrias, does that seem reasonable?

If I have file content assertions in my test cases, should that be sufficient for ensuring my generator is producing correct output?

**Comment by SBoudrias** [comment]
You should pass the `force` option rather than the property you're using (that is probably not working on the last version anyway).

`.withOptions({ force: true })`
