### ISSUE TITLE
Lodash interpolates ${...} in Yaml files but not in other file types

### ISSUE THREAD

**Issue by andidev** [yeoman/generator#750]
When calling
```
this.template(resourceDir + '/config/_application.yml', templateDir + 'config/application.yml', this, {});
````

in the generator with the application.yml file containing the following
```yaml
maven:
    artifactId: ${project.artifactId}
    version: ${project.version}
```

lodash throws the following error:
```
undefined:10
((__t = (project.artifactId)) == null ? '' : __t) +
         ^
ReferenceError: project is not defined
    at eval (eval at template (/Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:10:10)
    at JhipsterGenerator.underscore [as _engine] (/Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/lib/util/engines.js:31:45)
    at JhipsterGenerator.engine (/Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/lib/actions/actions.js:314:10)
    at JhipsterGenerator.template (/Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/lib/actions/actions.js:289:15)
    at JhipsterGenerator.app (/Users/anders/Workspace/generator-jhipster/app/index.js:461:10)
    at /Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

If the file extension of the application.yml file would be application.xml there generation works and `${project.artifactId}` is stayed intact.

**Comment by andidev** [comment]
Maybe this is the expected behaviour. Solved this issue by calling 
```
this.template(resourceDir + '/config/_application.yml', resourceDir + 'config/application.yml', this, { interpolate: /<%=(.+?)%>/g });
```

**Comment by kevva** [comment]
We're using `<% %>` tags. See something like https://github.com/yeoman/generator-webapp/blob/master/app/templates/_package.json for example.

**Comment by andidev** [comment]
The <% %> tags still works but it is also uses ${...}. 
I think that this is how the underscore templating engine works. You should set the interpolator specifically to only use the <% %> tags for some file types.
