### ISSUE TITLE
TypeError: Object #<Object> has no method 'on'

### ISSUE THREAD

**Issue by panuhorsmalahti** [yeoman/generator#762]
I'm running a generator and I'm suddenly getting this error. This might be caused by an updated dependency somewhere. I'm using yeoman-generator ~0.18.9.

```
C:\Program Files (x86)\nodejs\node_modules\generator-outotec\node_modules\yeoman-generator\lib\base.js:444
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: Object #<Object> has no method 'on'
    at run (C:\Program Files (x86)\nodejs\node_modules\generator-outotec\node_modules\yeoman-generator\lib\base.js:444:21)
    at Environment.run (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:330:20)
    at C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

The error is sometimes slightly different:
```
C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.all.js:9379
        throw e;
              ^
TypeError: Object #<Object> has no method 'on'
    at run (C:\Program Files (x86)\nodejs\node_modules\generator-outotec\node_modules\yeoman-generator\lib\base.js:444:21)
    at Environment.run (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:330:20)
    at module.exports (C:\Program Files (x86)\nodejs\node_modules\yo\lib\routes\run.js:20:11)
    at Router.navigate (C:\Program Files (x86)\nodejs\node_modules\yo\lib\router.js:36:30)
    at PromptUI.completed (C:\Program Files (x86)\nodejs\node_modules\yo\lib\routes\home.js:76:20)
    at PromptUI.onCompletion (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\inquirer\lib\ui\prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1965:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1902:14)
    at AutoDetachObserverPrototype.completed (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.all.js:9397:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Program Files (x86)\nodejs\node_modules\yo\node_modules\inquirer\node_modules\rx\dist\rx.all.js:1902:14)
```

Someone else has the same error: http://stackoverflow.com/questions/28536753/yo-polymer-building-error

**Comment by panuhorsmalahti** [comment]
I added console logging to the two separate places where sharedFs is being created in yeoman-environment/lib/environment.js, but I don't see the logging. It seems like the memFs object is not being created before used.

**Comment by panuhorsmalahti** [comment]
Fixed by updating yo (npm install -g yo).

**Comment by duranmla** [comment]
Thanks!

**Comment by gruppjo** [comment]
Yes, thank you!

**Comment by dreamerkumar** [comment]
You saved the day for me. Thank you!

**Comment by doomsbuster** [comment]
@panuhorsmalahti you saved hours for me. updating yo fixes this issue. Note installing gulp-karma didnt help
