### ISSUE TITLE
Error when calling this.gruntfile methods

### ISSUE THREAD

**Issue by maxtherocket** [yeoman/generator#777]
Anytime I try to use any of the this.gruntfile functionality, within the 'writing' method, for example:

```
writing: function(){
   this.gruntfile.insertVariable('loader', 'require("load-grunt-tasks")(grunt)');
}
```

I get the following error:

```
to: wrong arguments

toEnd: wrong arguments


events.js:85
      throw er; // Unhandled 'error' event
            ^
AssertionError: /Users/max/projects/generator-jam3-sandbox/Gruntfile.js doesn't exist
    at EditionInterface.module.exports [as read] (/Users/max/projects/generator-jam3/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read.js:13:3)
    at module.exports.Object.defineProperty.get (/Users/max/projects/generator-jam3/node_modules/yeoman-generator/lib/base.js:161:33)
    at module.exports.yeoman.generators.Base.extend.initializing.initGruntfile (/Users/max/projects/generator-jam3/generators/app/index.js:75:8)
    at /Users/max/projects/generator-jam3/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by SBoudrias** [comment]
Which version are you using?

**Comment by maxtherocket** [comment]
yo@1.4.6 
yeoman-generator@0.18.10

**Comment by kevva** [comment]
> AssertionError: /Users/max/projects/generator-jam3-sandbox/Gruntfile.js doesn't exist

Does it?

**Comment by maxtherocket** [comment]
No it doesn't.

From what I've read in this issue: https://github.com/yeoman/generator/issues/744 Gruntfile.js gets created only when accessing this.gruntfile, but it doesn't get created for some reason.

Here's the snippet:

https://github.com/yeoman/generator/blob/b611741e98710e2737080eab6e8bb5e8521fa4ee/lib/base.js#L157-L179

**Comment by SBoudrias** [comment]
I still need to investigate the cause (maybe this weekend), but it seems like a legitimate bug.

**Comment by SBoudrias** [comment]
Hey @maxtherocket, I'm unable to reproduce. My guess is one of the dependencies (probably `mem-fs-editor`) is out-dated.

Can you try running `npm update` and retry running it?

**Comment by SBoudrias** [comment]
Closing due to inactivity, we'll reopen if we have a response and the problem persist.

**Comment by fordlee404** [comment]
I  have also met this problem. My generator works well, but when I remove the `node_modules` dir and `npm install`, the generator run fails.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
AssertionError: /Users/ford/Codes/yeoman_test/test-fordlee404/Gruntfile.js doesn't exist
    at EditionInterface.module.exports [as read] (/Users/ford/Codes/yeoman_test/generator-fordlee404/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read.js:13:3)
    at Base.Object.defineProperty.get (/Users/ford/Codes/yeoman_test/generator-fordlee404/node_modules/yeoman-generator/lib/base.js:161:33)
    at module.exports.yeoman.generators.Base.extend.writing.gruntfile (/Users/ford/Codes/yeoman_test/generator-fordlee404/app/index.js:189:11)
    at /Users/ford/Codes/yeoman_test/generator-fordlee404/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

Then I use the [gruntfile-editor](https://github.com/SBoudrias/gruntfile-editor) to replace the `this.gruntfile` method. The problem fixed.

My generator is [generator-fordlee404](https://github.com/fordlee404/generator-fordlee404), the problem happens on `gruntfile-bug` branch, fixed it on `fix-gruntfile-editor` branch.

**Comment by fordlee404** [comment]
It fixed!  I see some changs (see below) in `base.js` file and test. 
```javascript
// Only instantiate the Gruntfile API when requested
  Object.defineProperty(this, 'gruntfile', {
    get: function () {
      if (!this.env.gruntfile) {
        var gruntfile = '';
        var gruntPath = this.destinationPath('Gruntfile.js');

        if (this.fs.exists(gruntPath)) {
          gruntfile = this.fs.read(gruntPath);
        }

        this.env.gruntfile = new GruntfileEditor(gruntfile);
      }

      // Schedule the creation/update of the Gruntfile
      this.env.runLoop.add('writing', function (done) {
        this.fs.write(
          this.destinationPath('Gruntfile.js'),
          this.env.gruntfile.toString()
        );
        done();
      }.bind(this), { once: 'gruntfile:write' });

      return this.env.gruntfile;
    }
  });
```
