### ISSUE TITLE
helpers.run() confuses package.json for subgenerator also named package

### ISSUE THREAD

**Issue by Freyert** [yeoman/generator#779]
Me again, goofing around with `generator-generator`. If you name a subgenerator `package`, when running tests `helpers.run(path.join(__dirname, '../package'))` gets confused and loads `package.json` instead of the generator located in `../package/index.js`.

Renaming the folder fixes the problem. Clone the repo below and run `npm test`. You'll see this error.
```
  1) Package:package "before all" hook:
     Uncaught TypeError: object is not a function
      at Environment.instantiate (/Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:282:10)
      at Environment.create (/Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/node_modules/yeoman-environment/lib/environment.js:259:15)
      at RunContext._run (/Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/lib/test/run-context.js:81:29)
      at RunContext.<anonymous> (/Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/lib/test/run-context.js:51:10)
      at /Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:5296:33
      at /Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/lib/test/helpers.js:183:5
      at next (/Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/node_modules/rimraf/rimraf.js:70:7)
      at CB (/Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/node_modules/rimraf/rimraf.js:106:9)
      at /Users/fultonbyrne/Desktop/generator-package/node_modules/yeoman-generator/node_modules/rimraf/rimraf.js:132:14
      at Object.oncomplete (fs.js:107:15)
```

https://github.com/Freyert/bug-subgenerator-package.git

**Comment by SBoudrias** [comment]
This is a bug in `yeoman-environment`.

This is because we always take the path and `require.resolve()` it. This mean any file that can be required (json or js) will take precedence over a folder name.

A potential fix might be to always append a `/` at the end of paths before resolving them to a specific file.

PR welcomed.

**Comment by Freyert** [comment]
I would love to! I'll get to work on it asap.

**Comment by Freyert** [comment]
@SBoudrias, as I've been working on this I've come to think that altering the expected behavior of `Environment.prototype.resolveModulePath` could have some undesirable side effects and maybe it would be more helpful in the long run to add a more explicit error message.

**Comment by SBoudrias** [comment]
It won't have undesirable side effects, the current behavior is a bug :)
