### ISSUE TITLE
Error starting certain generators

### ISSUE THREAD

**Issue by busches** [yeoman/generator#781]
Running yo v1.4.5 and node v0.12.X (I've tried with .1 and .2) on Win 7 x64, I'm getting the below error when starting either `gulp-angular` or `ng-poly`. The generator `gulp-ng` works. All three work if I switch the engine from node to io.js v1.6.3.

```shell
C:\Users\buschs1\Desktop\test-gulp-angular2
λ yo gulp-angular
C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-gulp-angular\node_modules\yeoman-generator\lib\base.js:445:21)
    at Environment.run (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:331:20)
    at C:\Program Files\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

C:\Users\buschs1\Desktop\test-gulp-angular2
λ yo ng-poly
C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\yeoman-generator\lib\base.js:445
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: undefined is not a function
    at run (C:\Users\buschs1\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\yeoman-generator\lib\base.js:445:21)
    at Environment.run (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:331:20)
    at C:\Program Files\nodejs\node_modules\yo\lib\cli.js:91:9
    at Environment.resolver.lookup (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
    at init (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:66:7)
    at pre (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:53:3)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\yo\lib\cli.js:155:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

C:\Users\buschs1\Desktop\test-gulp-angular2
λ yo gulp-ng

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

This generator will generate a web app project using gulp, bower and angularjs.
```

I had opened an issue(https://github.com/Swiip/generator-gulp-angular/issues/464) against `gulp-angular`, but since the issue is shared between `gulp-angular` and `ng-poly`, they requested I open one here.

**Comment by SBoudrias** [comment]
Try `npm -g update yo`.

**Comment by busches** [comment]
Thanks for the tip. Running that came back with no updates, but since the version did say 1.4.5 I found out that it had yo installed in two places, with the `-g` location being 2nd on the path, so it was updated but not being picked up.

**Comment by SBoudrias** [comment]
@busches Note that in this case, the issue is a sub-dependency not being up to date. So running `update` would've updated dependencies of `yo`, which was the goal.

**Comment by busches** [comment]
Right, I had still had the extra old `yo` on the path and because `-g update` was referencing the new location further down the path. I've removed all the modules installed in the old location, so it shouldn't be a problem in the future. Thanks for the help!
