### ISSUE TITLE
Tests with test/helpers: fs.copyTpl and fs.copy cause trouble

### ISSUE THREAD

**Issue by nilssolanki** [yeoman/generator#825]
I recently set up some tests using the yeoman test/helpers and they work almost perfectly. Only `fs.copy` and `fs.copyTpl` see to cause a problem. My test is pretty simple:

    describe('2. HTML', function() {

        before(function(done) {
            this.timeout(0);
            helpers.run(path.join(generatorDir, 'app'))
                .inDir(path.join(__dirname, '.tmp'))
                .withGenerators([[helpers.createDummyGenerator(), 'mygen:frontend']])
                .withPrompts({
                    dry: true,
                    project: 'a',
                    type: 'html'
                })
                .on('end', done);
        });

        it('should work', function(done) {
            done();
        });
    });
});

And the copy operation:

    ...
    if (istextorbinary.isTextSync(file)) {
        this.fs.copyTpl(
            file,
            destinationPath,
            this.settings
        );
    } else {
        this.fs.copy(
            file,
            destinationPath
        );
    }
    ...

Both `this.fs.copy` and `this.fs.copyTpl` seem to trigger the following error. If I run the generator via `yo mygen` it works fine:

    1) mygen:app 2. HTML "before all" hook:
     Uncaught TypeError: this.adapter.log[result.action] is not a function
      at Conflicter.<anonymous> (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/lib/util/conflicter.js:192:36)
      at PromptUI.onCompletion (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:69:10)
      at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
      at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
      at AnonymousObserver.tryCatcher (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
      at AutoDetachObserverPrototype.completed (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
      at InnerObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
      at InnerObserver.tryCatcher (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
      at AutoDetachObserverPrototype.completed (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
      at AutoDetachObserver.tryCatcher (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
      at AutoDetachObserverPrototype.completed (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
      at InnerObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
      at InnerObserver.tryCatcher (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
      at AutoDetachObserverPrototype.completed (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
      at AutoDetachObserver.tryCatcher (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
      at AutoDetachObserverPrototype.completed (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
      at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
      at /Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/lib/utils/utils.js:53:13
      at /Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/lodash/index.js:7345:25
      at /Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:98:7
      at Immediate._onImmediate (/Users/myuser/Documents/Repositories/mygen/generator-mygen/node_modules/yeoman-generator/lib/test/adapter.js:39:5)
      at processImmediate [as _immediateCallback] (timers.js:368:17)

**Comment by SBoudrias** [comment]
Do you have a link to your actual generator?

**Comment by nilssolanki** [comment]
Wow, this is really strange. I copy pasted most of the generator to a new directory and it worked without a problem.

So I started to look at the differences. I saw that I had a `yo-rc.json` with the following content:

	{
		"generator-generator": {}
	}

Once I deleted it, the test passed. I'm not sure if this is my error or a yeoman problem...

**Comment by SBoudrias** [comment]
This is kind of your error. You shouldn't create temp test directory inside your generator folder. (e.g `.inDir(path.join(__dirname, '.tmp'))`)

Use `inTmpDir()` for more flexibility and robust behavior.

**Comment by nilssolanki** [comment]
@SBoudrias you should probably add this to the documentation, since it is neither here:
http://yeoman.io/authoring/testing.html
nor in the API:
http://yeoman.github.io/generator/helpers.html
