### ISSUE TITLE
Ambiguous error when destination package.json is not a valid JSON 

### ISSUE THREAD

**Issue by yvele** [yeoman/generator#827]
If the destination package.json already exists and has a syntax error in it (an extra comma in my example), running yo will throw an error like that one:

````text
undefined:42
  },
  ^
SyntaxError: Unexpected token }
    at Object.parse (native)
    at EditionInterface.module.exports [as readJSON] (/Users/yves/Work/generator-foo/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read-json.js:5:17)
    at Base.determineAppname (/Users/yves/Work/generator-foo/node_modules/yeoman-generator/lib/base.js:743:23)
    at Base (/Users/yves/Work/generator-foo/node_modules/yeoman-generator/lib/base.js:145:23)
    at new generator.constructor (/Users/yves/Work/generator-foo/generators/app/index.js:13:19)
    at Environment.instantiate (/Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:282:10)
    at Environment.create (/Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:259:15)
    at Environment.run (/Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:318:24)
    at /Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/lib/cli.js:99:9
    at Environment.resolver.lookup (/Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/lib/cli.js:72:7)
    at pre (/Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/lib/cli.js:59:3)
    at Object.<anonymous> (/Users/yves/.nvm/versions/node/v0.12.1/lib/node_modules/yo/lib/cli.js:153:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
````

That's not really explicit. I had to spend time to look at yeoman-generator source code to figure out what was the problem and that the generator itself was not in cause.

There are two ways to deal with an invalid package.json at destination:
- Throw an explicit error saying something like: *"Destination package.json is invalid, please fix to run the generator"*.
- Manage invalid destination package.json as *"normal"* case (+ output a warning?).

In my opinion I think yeoman should consider destination package.json syntax errors as a normal case.

In [base.js](https://github.com/yeoman/generator/blob/master/lib/base.js#L757), instead of:

````javascript
/**
 * Determines the name of the application.
 *
 * First checks for name in bower.json.
 * Then checks for name in package.json.
 * Finally defaults to the name of the current directory.
 * @return {String} The name of the application
 */
Base.prototype.determineAppname = function () {
  var appname = this.fs.readJSON(this.destinationPath('bower.json'), {}).name;

  if (!appname) {
    appname = this.fs.readJSON(this.destinationPath('package.json'), {}).name;
  }

  if (!appname) {
    appname = path.basename(this.destinationRoot());
  }

  return appname.replace(/[^\w\s]+?/g, ' ');
};
````

we could do something like:

````javascript
function readJSONSafe (filepath) {
  var json;

  try {
    json = this.fs.readJSON(filepath, {});
  } catch (e) {
    if (e.name !== 'SyntaxError') {
      throw e;
    }
    json = {};
  }

  return json;
}

/**
 * Determines the name of the application.
 *
 * First checks for name in bower.json.
 * Then checks for name in package.json.
 * Finally defaults to the name of the current directory.
 * @return {String} The name of the application
 */
Base.prototype.determineAppname = function () {
  var appname = readJSONSafe.call(this, this.destinationPath('bower.json')).name;

  if (!appname) {
    appname = readJSONSafe.call(this, this.destinationPath('package.json')).name;
  }

  if (!appname) {
    appname = path.basename(this.destinationRoot());
  }

  return appname.replace(/[^\w\s]+?/g, ' ');
};
````

With, of course `readJSONSafe` at an appropriate place. 

I would like your opinion before spending time making this clean and submitting a PR..

PS: I don't think yeoman-generator should output a warning as it is not his business and the developer will figure it out by him self (when using npm).

PPS: [mem-fs-editor](https://github.com/SBoudrias/mem-fs-editor) does not have a readJSON equivalent that does not throw on JSON syntax error.

**Comment by SBoudrias** [comment]
I think the correct fix would be to catch syntax errors in mem-fs-editor and re-throw the error specifying the file name.

**Comment by yvele** [comment]
Ok, I've created an [issue](https://github.com/SBoudrias/mem-fs-editor/issues/38) in [mem-fs-editor](https://github.com/SBoudrias/mem-fs-editor)

**Comment by SBoudrias** [comment]
Allright, I'll close here.
