### ISSUE TITLE
EJS throws error when trying to trim whitespace

### ISSUE THREAD

**Issue by nouveller** [yeoman/generator#828]
So I have a simple `copyTpl` call that templates `gulpfile.js`.

```js
this.fs.copyTpl(
  this.templatePath('_gulpfile.js'),
  this.destinationPath('gulpfile.js'),
  { sass: this.props.useSass }
);
```

The `gulpfile.js` is like so.

```js
var gulp = require('gulp');
<% if (sass) { %>
var sass = require('gulp-sass');
<% } %>

gulp.task('default', function() {
  console.log('Yo! This is just a plan ol\' default task');
});
```

When `this.props.useSass` is `true`, my output is:

```js
var gulp = require('gulp');

var sass = require('gulp-sass');


gulp.task('default', function() {
  console.log('Yo! This is just a plan ol\' default task');
});
```

I wanted to avoid that whitespace on line 2 produced from the conditional so I used EJS' `-%>` trimmed closing tag:

```js
var gulp = require('gulp');
<% if (sass) { -%>
var sass = require('gulp-sass');
<% } -%>

...
```

Which then throw this error when trying to be compiled.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token ;
    at Function (<anonymous>)
    at /Users/nouveller/Sites/generator-starters/node_modules/yeoman-generator/node_modules/lodash/index.js:10809:16
    at /Users/nouveller/Sites/generator-starters/node_modules/yeoman-generator/node_modules/lodash/index.js:11082:21
    at /Users/nouveller/Sites/generator-starters/node_modules/yeoman-generator/node_modules/lodash/index.js:8152:31
    at Function.template (/Users/nouveller/Sites/generator-starters/node_modules/yeoman-generator/node_modules/lodash/index.js:10808:20)
    at copy.process (/Users/nouveller/Sites/generator-starters/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:11:16)
    at applyProcessingFunc (/Users/nouveller/Sites/generator-starters/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:12:16)
    at EditionInterface.exports._copySingle (/Users/nouveller/Sites/generator-starters/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:55:24)
```

I mucked around with various things to see if I was doing it wrong and ended up writing a separate script outside of the generator to see if was an `mem-fs-editor`/`ejs` issue.

*index.js*

```js
var memFs = require('mem-fs');
var editor = require('mem-fs-editor');

var store = memFs.create();
var fs = editor.create(store);

console.log('Compiling file');

fs.copyTpl(
  './template.js',
  './compiled_template.js'
)

fs.commit([], function() {
  console.log('Complete');
});
```

*template.js*

```js
// at the top of file, should be no whitespace between the two comments
<% if (false) { -%>
var foo = 'bar';
<% } -%>
// files carries on...
```

And the result is:

```js
// at the top of file, should be no whitespace between the two comments
// files carries on...
```

No errors thrown and whitespace gone. So it appears to be an issue with the generator, any ideas?

**Comment by sindresorhus** [comment]
Make sure you're using the latest version of `yeoman-generator` as EJS is a pretty recent feature.

**Comment by nouveller** [comment]
@sindresorhus Yep, you're right, it was sitting at `0.19`. `0.20.1` fixes it up. Thank-you.

Dependency versions are our new "turn it off and on again".

**Comment by sindresorhus** [comment]
Yup, there's a reason I asked. It's far from the first time I've seen this happen, even for me :)
