### ISSUE TITLE
Error copyTpl : Arguments to path.join must be strings

### ISSUE THREAD

**Issue by jaumard** [yeoman/generator#848]
Hi,

I trying to create my own generator but when I want to copy with template I have an error.
Here is my code : 

    console.log(this.appname, this.appauthor);

    this.fs.copyTpl(this.templatePath('plugin.json'), this.destinationPath(this.appname + '/plugin.json', {
        name   : this.appname,
        author : this.appauthor
      }));

And the error : 

    TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Base.destinationPath (/Users/jaumard/IdeaProjects/LISAPluginGenerator/generator-lisa-plugin/node_modules/yeoman-generator/lib/base.js:728:20)
    at module.exports.yeoman.generators.Base.extend.writing.app (/Users/jaumard/IdeaProjects/LISAPluginGenerator/generator-lisa-plugin/generators/app/index.js:64:61)
    at /Users/jaumard/IdeaProjects/LISAPluginGenerator/generator-lisa-plugin/node_modules/yeoman-generator/lib/base.js:421:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)

And my file : 

    {
      "name"       : "<%= name %>",
      "version"    : "0.0.0",
      "description": "",
      "author"     : "<%= author %>",
      "events"     : [],
      "categories" : []
    }

The console.log give me my name and author param correctly so I don't understand what I'm doing wrong...

**Comment by jaumard** [comment]
My bad ! I put bracket in the wrong place ! 
Here is correct :

    this.fs.copyTpl(this.templatePath('plugin.json'), this.destinationPath(this.appname + '/plugin.json'), {
       name   : this.appname,
       author : this.appauthor
     });

Sorry for this
