### ISSUE TITLE
Error while configuring generator

### ISSUE THREAD

**Issue by cham26** [yeoman/generator#851]
i got this error after entering when prompted to select what Angular modules you would like to include as well:
create app/styles/main.css
/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/mkdirp/index.js:74
                    throw err0;
                          ^
Error: EACCES, permission denied '/home/cham/mytodo/app'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at sync (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/mkdirp/index.js:55:12)
    at Function.sync (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/mkdirp/index.js:61:24)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/actions/actions.js:106:12)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
cham@cham-Aspire-E3-111:~/mytodo$ 

I hope you can help me with this.
Please send me email at chamcee89@gmail.com

All the best,
Charmaine

**Comment by SBoudrias** [comment]
The relevant part is

> Error: EACCES, permission denied '/home/cham/mytodo/app'

You have a permission issue on your computer. You can probably fix it, it's not an issue on our side.

In the future, please open issues on the generator causing you issue. `yeoman/generator` is the framework to write generators, it's not generator-angular project.
