### ISSUE TITLE
Testing with tape

### ISSUE THREAD

**Issue by bucaran** [yeoman/generator#852]
Has anyone tried testing a generator with tap/tape?

```js
const join = require('path').join
const assert = require("yeoman-generator").assert
const helpers = require('yeoman-generator').test
const test = require("tape").test

helpers.run(join(__dirname, "./app"))
  .withOptions({ skipInstall: true })
  .withPrompts({ someOption: true })
  .on("end", function () {
    assert.file([
      '.editorconfig',
      '.gitignore',
      '.eslintrc',
      '.npmignore',
      '.travis.yml',
      'package.json',
      'index.js',
      'test.js',
      'README.md',
      'CHANGELOG.md'
    ])
    test("generator-tiny-es-nm:app", function (t) {
      t.ok(true, "generate template files")
      t.end()
    })
  })
```

I have tried both, wrapping everything inside the `test("...` and as shown in the example and both pass locally, but failed in Travis with:

```

> generator-tiny-es-nm@1.0.10 test /home/travis/build/bucaran/generator-tiny-es-nm
> tape test.js
TAP version 13
1..0
# time=312.004ms
/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
TypeError: Expected a string
    at module.exports (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/humanize-url/index.js:7:9)
    at null.<anonymous> (/home/travis/build/bucaran/generator-tiny-es-nm/app/index.js:67:31)
    at null.<anonymous> (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/lib/base.js:233:7)
    at PromptUI.onCompletion (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1793:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at AnonymousObserver.tryCatcher (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:5288:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1730:14)
    at InnerObserver.onCompleted (/home/travis/build/bucaran/generator-tiny-es-nm/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:3425:65)
npm ERR! Test failed.  See above for more details.
```

**Comment by bucaran** [comment]
Closing as I was able to fix the issue and test with tape.

**Comment by kkemple** [comment]
@bucaran can you please explain how you were able to do this?

**Comment by bucaran** [comment]
I don't remember all the details, but I created this[[1]] yeoman generator with those findings.

[1]: https://github.com/bucaran/generator-rise

**Comment by kkemple** [comment]
thanks for the quick reply! i was able to get it to work but I wanted a bit of a cleaner output, ended up with this...

(not committed yet, sorry for the long comment :wink:)

```javascript
import path from 'path'

import helpers from 'yeoman-test'
import assert from 'yeoman-assert'
import test from 'tape'

const options = {
  moduleName: 'test',
  moduleDescription: 'test',
  authorName: 'Test',
  authorEmail: 'test@test.com',
  keywords: 'awesome, module, test',
  repository: 'kkemple/test',
}

test('test', (t) => {
  helpers
    .run(path.resolve(__dirname, 'index.js'))
    .withOptions(options)
    .on('end', () => {
      try {
        assert.file([
          'src/index.js',
          'src/index.test.js',
          '.babelrc',
          '.eslintrc',
          '.eslintignore',
          '.gitignore',
          '.npmignore',
          '.codeclimate.yml',
          'circle.yml',
          'package.json',
          'readme.md',
          'CHANGELOG.md',
          'LICENSE.md',
        ])
      } catch (err) {
        t.fail(err)
      }

      t.pass('all files found')
      t.end()
    })
})

test('test', (t) => {
  helpers
    .run(path.resolve(__dirname, 'index.js'))
    .withPrompts(options)
    .on('end', () => {
      try {
        assert.fileContent('src/index.js', 'return \'test\'')
      } catch (err) {
        t.fail(err)
      }

      t.pass('src/index.js has proper module name')
      t.end()
    })
})

test('test', (t) => {
  helpers
    .run(path.resolve(__dirname, 'index.js'))
    .withPrompts(options)
    .on('end', () => {
      try {
        assert.fileContent('src/index.test.js', 'assert.equal(myModule(), \'test\', \'should return module name\')')
      } catch (err) {
        t.fail(err)
      }

      t.pass('src/index.test.js has proper module name')
      t.end()
    })
})

test('test', (t) => {
  helpers
    .run(path.resolve(__dirname, 'index.js'))
    .withPrompts(options)
    .on('end', () => {
      try {
        assert.fileContent('LICENSE.md', 'Test')
      } catch (err) {
        t.fail(err)
      }

      t.pass('LICENSE.md has proper author name')
      t.end()
    })
})

test('test', (t) => {
  helpers
    .run(path.resolve(__dirname, 'index.js'))
    .withPrompts(options)
    .on('end', () => {
      try {
        assert.fileContent('package.json', '"name": "test"')
        assert.fileContent('package.json', '"description": "test"')
        assert.fileContent('package.json', '"url": "git+ssh://git@github.com/kkemple/test.git"')
        assert.fileContent('package.json', '"url": "https://github.com/kkemple/test/issues"')
        assert.fileContent('package.json', '"homepage": "https://github.com/kkemple/test#readme"')
        assert.fileContent('package.json', '"keywords": [\"awesome\", \"module\", \"test\"]')
        assert.fileContent('package.json', '"author": "Test <test@test.com>"')
      } catch (err) {
        t.fail(err)
      }

      t.pass('package.json has proper properties')
      t.end()
    })
})

test('test', (t) => {
  helpers
    .run(path.resolve(__dirname, 'index.js'))
    .withPrompts(options)
    .on('end', () => {
      try {
        assert.fileContent('README.md', 'test')
        assert.fileContent('README.md', 'https://codeclimate.com/github/kkemple/test/badges/gpa.svg')
        assert.fileContent('README.md', 'https://codeclimate.com/github/kkemple/test/badges/coverage.svg')
        assert.fileContent('README.md', 'https://codeclimate.com/github/kkemple/test/badges/issue_count.svg')
        assert.fileContent('README.md', 'https://codeclimate.com/github/kkemple/test')
        assert.fileContent('README.md', 'https://circleci.com/gh/kkemple/test.svg?style=svg')
        assert.fileContent('README.md', '`npm install test`')
      } catch (err) {
        t.fail(err)
      }

      t.pass('README.md has proper properties')
      t.end()
    })
})

```
