### ISSUE TITLE
angular2-generator issue

### ISSUE THREAD

**Issue by mjain1990** [yeoman/generator#854]
Hi Team,

I have installed a angular2 generator using ``npm install -g yo generator-angular2``

but on using gulp serve its not working and showing error to me 

    Failed to load resource: the server responded with a status of 404 (Not Found)
    es6-module-loader.js:7 Potentially unhandled rejection [2] TypeError: Error loading "index" at http://localhost:8000/index.js
    Cannot convert object to primitive value
        at http://localhost:8000/lib/system.js:1:4824
        at Array.<anonymous> (http://localhost:8000/lib/angular2.js:3888:7)
        at d (http://localhost:8000/lib/system.js:1:5501)
        at d (http://localhost:8000/lib/system.js:1:5364)
        at d (http://localhost:8000/lib/system.js:1:5364)
        at l (http://localhost:8000/lib/system.js:1:4590)
        at Object.execute (http://localhost:8000/lib/system.js:1:8278)
        at o (http://localhost:8000/lib/es6-module-loader.js:7:18496)
        at p (http://localhost:8000/lib/es6-module-loader.js:7:18868)
        at j (http://localhost:8000/lib/es6-module-loader.js:7:16406)

**Comment by arthurvr** [comment]
That's an issue with the generator you're using, not an issue with yeoman-generator. Report this at https://github.com/swirlycheetah/generator-angular2 instead.
