### ISSUE TITLE
Can't extend Base in Node 5.0.0 because of `constructor` method

### ISSUE THREAD

**Issue by bentruyman** [yeoman/generator#869]
The following code will not execute:

```javascript
// index.js
const generators = require("yeoman-generator");

const Generator = generators.Base.extend({
  constructor() {
    generators.Base.apply(this, arguments);
  }
});

const instance = new Generator();
```

Simply running this with `node index.js` on Node 5.0.0 results in the following:

```
/Users/someone/Desktop/yoyo/index.js:9
const instance = new Generator();
                 ^

TypeError: constructor() {
    generators.Base.apply(this, arguments);
  } is not a constructor
    at Object.<anonymous> (/Users/someone/Desktop/yoyo/index.js:9:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

Now, I can remedy this by the following:

```javascript
const generators = require("yeoman-generator");

const Generator = generators.Base.extend({
  constructor: function () {
    generators.Base.apply(this, arguments);
  }
});

const instance = new Generator();
```

But this violates my `eslint` rules which requires functions to use the shortened version when possible.

**Comment by bentruyman** [comment]
This was using `yeoman-generator@0.21.1`.

**Comment by bentruyman** [comment]
This looks like it is more of an ES6 restriction than a yeoman-generator problem.

**Comment by SBoudrias** [comment]
Go all the way:

```js
class Generator extend generators.Base {
  constructor() {}
}
```

And you can now call `super` rather than manually doing it.

**Comment by bentruyman** [comment]
As you said, this works:
```javascript
class Generator extend generators.Base {
  constructor() {
    super(...arguments);
  }
}
```

Closing. Thanks @SBoudrias.
