### ISSUE TITLE
Generators with ES6 classes do not work when using a constructor

### ISSUE THREAD

**Issue by davidreher** [yeoman/generator#889]
Since [Node4](http://kangax.github.io/compat-table/es6/#node4) and [Node5](http://kangax.github.io/compat-table/es6/#node5) do support the class syntax, we decided to write our generators as ES6-Classes.

When overwriting the default constructor like so:
```javascript
class Generator extends generators.Base {
  constructor() {
    console.log('calling super constructor');
    super(arguments);
  }
}
```
you receive the following error message:
```
calling super constructor

assert.js:90
  throw new assert.AssertionError({
  ^
 AssertionError: You must provide the environment object. Use env#create() to create a new generator.
    at Generator.Base (...\node_modules\yeoman-generator\lib\base.js:104:3)
    at Generator (...\generators\app\index.js:14:45)
    at Environment.instantiate (...\node_modules\yeoman-environment\lib\environment.js:297:10)
    at Environment.create (...\node_modules\yeoman-environment\lib\environment.js:274:15)
    at Environment.run (...\yeoman-environment\lib\environment.js:333:24)
    at ...\node_modules\yo\lib\cli.js:99:9
```

What I tried as well is using `generators.Base.apply` like so:
 ```javascript
  constructor() {
    console.log('calling super constructor');
    generators.Base.apply(arguments);
  }
```

Then I am getting
```
calling super constructor
...\node_modules\yeoman-generator\lib\base.js:86
  this.option('help', {
       ^

TypeError: this.option is not a function
    at Object.Base (...\node_modules\yeoman-generator\lib\base.js:86:8)
    at Generator (...\generators\app\index.js:15:21)
    at Environment.instantiate (...\node_modules\yeoman-environment\lib\environment.js:297:10)
    at Environment.create (...\node_modules\yeoman-environment\lib\environment.js:274:15)
    at Environment.run (...\node_modules\yeoman-environment\lib\environment.js:333:24)
    at ...\node_modules\yo\lib\cli.js:99:9
```

If you do not use the constructor in your Generators everything works fine ^^

Can someone help me with this one?

**Comment by davidreher** [comment]
Ok, got it working myself. You need to use:
```javascript
class Generator extends generators.Base {
  constructor(args, options) {
    super(args, options);
  }
}
```
