### ISSUE TITLE
How to support older versions of node (<=0.12.x) when using yeoman-generator v0.22?

### ISSUE THREAD

**Issue by tomwayson** [yeoman/generator#904]
I'm trying to update our generator from being based on yeoman-generator v0.17 to latest (v0.22). I've updated my package.json (according to output of the latest generator-generator, other than the dep on v0.19 which I've replaced w/ v.022), and made the needed changes to my generator and test files. Details can be seen [in this commit](https://github.com/tomwayson/generator-esri-appbuilder-js/commit/26923355a6ec1216235cd1945ed6df4d18b903ef). The generator runs fine on node v4 and up.

However, the problem is that I get **Error; Cannot find module 'yeoman-assert'** when running on older versions of node (via nvm), both in [TravisCI on v0.10](https://travis-ci.org/Esri/generator-esri-appbuilder-js/jobs/108064008) and my Windows machine on v0.10 and v0.12 (see below for err output on v.0.12). 
```bash
$ node --version
v0.12.9

$ npm --version
2.14.9

$ npm test
> generator-esri-appbuilder-js@2.0.0 test c:\code\git\generator-esri-appbuilder-js
> mocha

module.js:338
    throw err;
          ^
Error: Cannot find module 'yeoman-assert'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\code\git\generator-esri-appbuilder-js\test\test-creation.js:4:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at c:\code\git\generator-esri-appbuilder-js\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (c:\code\git\generator-esri-appbuilder-js\node_modules\mocha\lib\mocha.js:216:14)
    at Mocha.run (c:\code\git\generator-esri-appbuilder-js\node_modules\mocha\lib\mocha.js:468:10)
    at Object.<anonymous> (c:\code\git\generator-esri-appbuilder-js\node_modules\mocha\bin\_mocha:403:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

I'm able to get past this error and run the tests by explicitly adding adding mkdrip, yeoman-assert, and yeoman-test to the devDependencies and runing `npm install`.

My question is, should I have to do that? Is that the right way to support older versions of node?

Even after explicitly installing the above devDependencies it appeared as though most, if not all of my tests were failing due to to timeout errors. I was able to get them to pass by upping the mocha timeout with  `--timeout 1000`

**Comment by SBoudrias** [comment]
Every dependency should ALWAYS be defined in the `package.json` file. Your issue is not related to older node version, it's probably due to nvm and which packages are globally installed in each environment.

**Comment by tomwayson** [comment]
@SBoudrias thank you!

That makes sense. I guess using yeoman-assert and yeoman-test directly came in some of the deprecation releases after 0.19 (which is why the 0.19 based generator-generator doesn't include those as devDependencies in package.json). I now see the [related open issue](https://github.com/yeoman/generator-generator/issues/140).
