### ISSUE TITLE
this.directory() is not working after yeoman update

### ISSUE THREAD

**Issue by Aswini999** [yeoman/generator#914]
I have updated yeoman and npm recently. After the update, this.directory('src', 'src') is not working.

Error message:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: toString failed
    at Buffer.toString (buffer.js:397:11)
    at EditionInterface.module.exports [as write] (/Users/macadmin/com.demo.app/generator/node_modules/mem-fs-editor/lib/actions/write.js:18:24)
    at EditionInterface.exports._copySingle (/Users/macadmin/com.demo.app/generator/node_modules/mem-fs-editor/lib/actions/copy.js:54:8)
    at EditionInterface.exports.copy (/Users/macadmin/Bcom.demo.app/generator/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at copy (/Users/com.demo.app/generator/node_modules/yeoman-generator/lib/actions/actions.js:41:13)
    at _directory (/Users/macadmin/com.demo.app/generator/node_modules/yeoman-generator/lib/actions/actions.js:165:8)
    at directory (/Users/macadmin/com.demo.app/generator/node_modules/yeoman-generator/lib/actions/actions.js:182:15)
    at yeoman.generators.Base.extend.projectfiles (/Users/macadmin/com.demo.app/generator/app/index.js:29:10)
    at /Users/macadmin/com.demo.app/generator/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Please advice ASAP since it is blocking our execution

**Comment by iamstarkov** [comment]
downgrade your yeoman if its urgent

**Comment by SBoudrias** [comment]
Any chance your files have weird encoding or similar issues?

**Comment by Aswini999** [comment]
@SBoudrias , This was working previously before Yeoman update. Is there any issues with this.directory() after the update. Kindly provide the syntax if I'm using it in wrong way.

**Comment by SBoudrias** [comment]
Well, first of all. Which version to which version?

Did you check the changelog? We're still pre 1.0 and release breaking changes with each bumps.

**Comment by eddiemonge** [comment]
@Aswini999 are you still having this problem?

**Comment by Aswini999** [comment]
Yes. We do.. Since we can't downgrade node version, we downgraded yo and yeoman versions
